import { Metadata } from 'next'
import Link from 'next/link'

export const metadata: Metadata = {
  title: 'Legal Disclaimer | Prow®',
  description: 'Legal Disclaimer for Prow® - Important notices about our services and content.',
}

export default function LegalDisclaimerPage() {
  return (
    <div className="py-16 px-6 md:px-12">
      <div className="max-w-3xl mx-auto">
        <h1 className="text-4xl md:text-5xl font-heading font-bold mb-4">Legal Disclaimer</h1>
        <p className="text-text/60 mb-12">Effective Date: August 1, 2025</p>

        <div className="prose prose-lg max-w-none prose-headings:font-heading prose-headings:font-semibold prose-p:text-text/80 prose-li:text-text/80">
          <section className="mb-12">
            <h2 className="text-2xl mb-4">General Information</h2>
            <p>
              The information provided by Prow Co. (&quot;Prow,&quot; &quot;we,&quot; &quot;us,&quot; or &quot;our&quot;) on prowco.ai and through our products and services, including Prow® and ProwPay™, is for general informational purposes only.
            </p>
            <p>
              All information on the Site and through our Services is provided in good faith. However, we make no representation or warranty of any kind, express or implied, regarding the accuracy, adequacy, validity, reliability, availability, or completeness of any information on the Site or through our Services.
            </p>
          </section>

          <section className="mb-12">
            <h2 className="text-2xl mb-4">No Professional Advice</h2>
            <p>
              The content on our website and through our Services does not constitute legal, financial, tax, investment, medical, or any other professional advice. You should not take any action based solely on the information provided without first consulting with a qualified professional.
            </p>
            <p className="mt-4">
              <strong>Prow® is a technology platform.</strong> Any insights, analyses, or recommendations generated by our AI-powered Services are intended to assist with information organization and decision-making support. They should not be considered as definitive professional guidance.
            </p>
          </section>

          <section className="mb-12">
            <h2 className="text-2xl mb-4">User Responsibility</h2>
            <p>
              You acknowledge and agree that you are solely responsible for:
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Any decisions you make based on information provided through our Services</li>
              <li>The accuracy and legality of any content you upload to the platform</li>
              <li>Compliance with applicable laws and regulations in your jurisdiction</li>
              <li>Verifying any information before relying on it for business or personal decisions</li>
            </ul>
          </section>

          <section className="mb-12">
            <h2 className="text-2xl mb-4">Third-Party Links and Services</h2>
            <p>
              Our website and Services may contain links to third-party websites, services, or resources that are not owned or controlled by Prow Co. We are not responsible for the content, accuracy, or privacy practices of any third-party websites or services.
            </p>
            <p className="mt-4">
              The inclusion of any links does not necessarily imply a recommendation or endorsement of the views expressed within them. We have no control over the nature, content, and availability of those sites.
            </p>
          </section>

          <section className="mb-12">
            <h2 className="text-2xl mb-4">AI-Generated Content</h2>
            <p>
              Our Services utilize artificial intelligence to analyze data and generate insights. While we strive for accuracy, AI-generated content may occasionally contain errors, inaccuracies, or outdated information.
            </p>
            <p className="mt-4 font-semibold">
              AI-generated insights should be reviewed and verified by qualified professionals before being used as the basis for important decisions.
            </p>
          </section>

          <section className="mb-12">
            <h2 className="text-2xl mb-4">Trademarks and Intellectual Property</h2>
            <p>
              Prow® and ProwPay™ are trademarks of Prow Co. All other trademarks, service marks, and trade names referenced on this website are the property of their respective owners.
            </p>
            <p className="mt-4">
              Nothing contained on this website should be construed as granting any license or right to use any trademark without the prior written permission of Prow Co. or such third party that may own the trademarks.
            </p>
          </section>

          <section className="mb-12">
            <h2 className="text-2xl mb-4">Limitation of Liability</h2>
            <p>
              Under no circumstances shall Prow Co., its directors, employees, or agents be liable for any direct, indirect, punitive, incidental, special, or consequential damages arising out of or in any way connected with:
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Your use of or inability to use our website or Services</li>
              <li>Any information obtained from or through our Services</li>
              <li>Any errors or omissions in the content</li>
              <li>Unauthorized access to or use of our servers and/or personal information stored therein</li>
            </ul>
          </section>

          <section className="mb-12">
            <h2 className="text-2xl mb-4">Governing Law</h2>
            <p>
              This Legal Disclaimer and your use of the website and Services shall be governed by and construed in accordance with the laws of the State of California, United States, without regard to its conflict of law provisions.
            </p>
          </section>

          <section className="mb-12">
            <h2 className="text-2xl mb-4">Related Legal Documents</h2>
            <p>
              For complete information about your rights and obligations when using our Services, please also review:
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li><Link href="/legal/terms" className="text-[#0066CC] hover:underline">Terms of Service</Link></li>
              <li><Link href="/legal/privacy" className="text-[#0066CC] hover:underline">Privacy Policy</Link></li>
            </ul>
          </section>

          <section className="mb-12">
            <h2 className="text-2xl mb-4">Contact Us</h2>
            <p>
              If you have any questions about this Legal Disclaimer, please contact us:
            </p>
            <p className="mt-4">
              <strong>Email:</strong> <a href="mailto:info@prowco.ai" className="text-[#0066CC] hover:underline">info@prowco.ai</a><br />
              <strong>Address:</strong> Prow Co., Los Angeles, USA
            </p>
          </section>
        </div>
      </div>
    </div>
  )
}
